# Generated by Django 4.2.2 on 2024-07-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ethereumAddress',
            field=models.CharField(default='0x0000000000000000000000000000000000000000', max_length=50),
        ),
    ]
